### PR TITLE
Add of TaskLogger.java

### PR DESCRIPTION
**Pull request by mzemmour**

### CODE REVIEW

**Comment by yairogen** [comment]
@mzemmour can you please explain the changes?

**Comment by mzemmour** [comment]
The changes are: adding a Task Logger to log tasks running in the background, (in the log the type field will be ‘Task’)

I also added a JobLogger that is an abstract class that is extended by the Task and Scheduler Logger.

Thanks,

Michael

**Comment by yairogen** [comment]
@mzemmour what is the difference between task and scheduler?

**Comment by mzemmour** [comment]
Scheduler = job that run at a specific time interval
Task = a background task that is ran by a user request (we sometime should return immediately 200OK but continue to process a task in the background)

Thanks,

Michael

**Comment by yairogen** [comment]
@mzemmour please update version in pom. **+1 to the second digit.**

**Comment by mzemmour** [comment]
Done.

Thanks,

Michael

**Pull request merged**
